# Generated by Django 5.2.6 on 2025-09-19 18:33

import django.db.models.deletion
import habits.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку",
                        max_length=255,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку", verbose_name="Время выполнения"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Конкретное действие, которое представляет собой привычка",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли привычка приятной (вознаграждением)",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после выполнения",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки (раз в сколько дней)",
                        validators=[habits.validators.validate_habit_frequency],
                        verbose_name="Периодичность (в днях)",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки",
                        validators=[habits.validators.validate_habit_duration],
                        verbose_name="Время на выполнение (в секундах)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Могут ли другие пользователи видеть эту привычку",
                        verbose_name="Признак публичности",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка, которая выполняется после основной",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
    ]
