# Generated by Django 5.2.6 on 2025-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("manager", "Менеджер")],
                default="user",
                max_length=10,
                verbose_name="Роль",
            ),
        ),
    ]
