# Generated by Django 5.2.6 on 2025-09-22 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Уникальный идентификатор чата для Telegram уведомлений",
                null=True,
                unique=True,
                verbose_name="ID чата в Telegram",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_notifications",
            field=models.BooleanField(
                default=True, help_text="Включены ли уведомления в Telegram", verbose_name="Telegram уведомления"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Username в Telegram"),
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "chat_id",
                    models.BigIntegerField(
                        help_text="Уникальный идентификатор чата с пользователем",
                        unique=True,
                        verbose_name="ID чата в Telegram",
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Username в Telegram"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата подключения")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram пользователь",
                "verbose_name_plural": "Telegram пользователи",
            },
        ),
    ]
